# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYPITP312' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!

  # Pods for NYPITP312
  pod 'Material', '~> 2.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Google/SignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'OAuthSwift', '~> 1.1.0'
  
  target 'NYPITP312Tests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Material', '~> 2.0'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Google/SignIn'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
  end

  target 'NYPITP312UITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Material', '~> 2.0'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Google/SignIn'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
  end

end
