# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYPITP312' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYPITP312
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  target 'NYPITP312Tests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
  end

  target 'NYPITP312UITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
  end

end
